#
# LICENSED UNDER APACHE LICENSE 2.0
# COPYRIGHT 2018 615283 (James Conway) & lewis2470(Lewis Hitching)
# DO NOT REMOVE THIS NOTICE FROM THIS FILE OR ANY OTHER FILE WITHIN THIS REPOSITORY CONTAINING THIS NOTICE
#

name: CondensePlugin
version: 1.1
main: net.brocraftlive.condenser.CondensePlugin
authors: [615283, lewis2470]
commands:
  condense:
    description: Condense ingots to blocks
    usage: /condense
permissions:
  condenser.use:
    description: Allows use of /condense command
    default: true
